### ISSUE TITLE
API 구현

### ISSUE THREAD

**Issue by KOREAparksh** [SongSongPaPa/learn_nest#6]
## Todo
Auth, user관련 API 구현

</br>

## Task
- [ ] POST /auth/signin
- [ ] POST /auth/signup
- [ ] POST /auth/token
- [ ] POST /auth/two-factor
- [ ] PUT /auth/two-factor

- [ ] PUT /user/profile
- [ ] GET /user/nickname?name="{name}" (닉네임 중복검사)
- [ ] GET /user/detail
